#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_FINGERPRINT_MTK_CDFINGER_V31)	+=  cdfinger_v31/
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_MICROARRAY_FINGERPRINT) += microarray_fp/
